//
//  ComplexOrderStrategyType.swift
//  ccSchwabManager
//
//  Created by Harold Tomlinson on 2025-05-24.
//

import Foundation

/**
 complexOrderStrategyType    complexOrderStrategyTypestring
 Enum:
 [ NONE, COVERED, VERTICAL, BACK_RATIO, CALENDAR, DIAGONAL, STRADDLE, STRANGLE, COLLAR_SYNTHETIC, BUTTERFLY, CONDOR, IRON_CONDOR, VERTICAL_ROLL, COLLAR_WITH_STOCK, DOUBLE_DIAGONAL, UNBALANCED_BUTTERFLY, UNBALANCED_CONDOR, UNBALANCED_IRON_CONDOR, UNBALANCED_VERTICAL_ROLL, MUTUAL_FUND_SWAP, CUSTOM ]

 */


public enum ComplexOrderStrategyType: String, Codable, CaseIterable
{
    case NONE = "NONE"
    case COVERED = "COVERED"
    case VERTICAL = "VERTICAL"
    case BACK_RATIO = "BACK_RATIO"
    case CALENDAR = "CALENDAR"
    case DIAGONAL = "DIAGONAL"
    case STRADDLE = "STRADDLE"
    case STRANGLE = "STRANGLE"
    case COLLAR_SYNTHETIC = "COLLAR_SYNTHETIC"
    case BUTTERFLY = "BUTTERFLY"
    case CONDOR = "CONDOR"
    case IRON_CONDOR = "IRON_CONDOR"
    case VERTICAL_ROLL = "VERTICAL_ROLL"
    case COLLAR_WITH_STOCK = "COLLAR_WITH_STOCK"
    case DOUBLE_DIAGONAL = "DOUBLE_DIAGONAL"
    case UNBALANCED_BUTTERFLY = "UNBALANCED_BUTTERFLY"
    case UNBALANCED_CONDOR = "UNBALANCED_CONDOR"
    case UNBALANCED_IRON_CONDOR = "UNBALANCED_IRON_CONDOR"
    case UNBALANCED_VERTICAL_ROLL = "UNBALANCED_VERTICAL_ROLL"
    case MUTUAL_FUND_SWAP = "MUTUAL_FUND_SWAP"
    case CUSTOM = "CUSTOM"
}
