//
//  SapiTransactionFixedIncomeType.swift
//  ccSchwabManager
//
//  Created by Harold Tomlinson on 2025-04-29.
//

import Foundation

/**
 string
 Enum:
 [ BOND_UNIT, CERTIFICATE_OF_DEPOSIT, CONVERTIBLE_BOND, COLLATERALIZED_MORTGAGE_OBLIGATION, CORPORATE_BOND, GOVERNMENT_MORTGAGE, GNMA_BONDS, MUNICIPAL_ASSESSMENT_DISTRICT, MUNICIPAL_BOND, OTHER_GOVERNMENT, SHORT_TERM_PAPER, US_TREASURY_BOND, US_TREASURY_BILL, US_TREASURY_NOTE, US_TREASURY_ZERO_COUPON, AGENCY_BOND, WHEN_AS_AND_IF_ISSUED_BOND, ASSET_BACKED_SECURITY, UNKNOWN ]
 */

public enum SapiTransactionFixedIncomeType: String, Codable, CaseIterable
{
    case BOND_UNIT = "BOND_UNIT"
    case CERTIFICATE_OF_DEPOSIT = "CERTIFICATE_OF_DEPOSIT"
    case CONVERTIBLE_BOND = "CONVERTIBLE_BOND"
    case COLLATERALIZED_MORTGAGE_OBLIGATION = "COLLATERALIZED_MORTGAGE_OBLIGATION"
    case CORPORATE_BOND = "CORPORATE_BOND"
    case GOVERNMENT_MORTGAGE = "GOVERNMENT_MORTGAGE"
    case GNMA_BONDS = "GNMA_BONDS"
    case MUNICIPAL_ASSESSMENT_DISTRICT = "MUNICIPAL_ASSESSMENT_DISTRICT"
    case MUNICIPAL_BOND = "MUNICIPAL_BOND"
    case OTHER_GOVERNMENT = "OTHER_GOVERNMENT"
    case SHORT_TERM_PAPER = "SHORT_TERM_PAPER"
    case US_TREASURY_BOND = "US_TREASURY_BOND"
    case US_TREASURY_BILL = "US_TREASURY_BILL"
    case US_TREASURY_NOTE = "US_TREASURY_NOTE"
    case US_TREASURY_ZERO_COUPON = "US_TREASURY_ZERO_COUPON"
    case AGENCY_BOND = "AGENCY_BOND"
    case WHEN_AS_AND_IF_ISSUED_BOND = "WHEN_AS_AND_IF_ISSUED_BOND"
    case ASSET_BACKED_SECURITY = "ASSET_BACKED_SECURITY"
    case UNKNOWN = "UNKNOWN"
}
