//
//  SapiTransactionEquityType.swift
//  ccSchwabManager
//
//  Created by Harold Tomlinson on 2025-04-28.
//

import Foundation

/**
 Enum:
 [ COMMON_STOCK, PREFERRED_STOCK, DEPOSITORY_RECEIPT, PREFERRED_DEPOSITORY_RECEIPT, RESTRICTED_STOCK, COMPONENT_UNIT, RIGHT, WARRANT, CONVERTIBLE_PREFERRED_STOCK, CONVERTIBLE_STOCK, LIMITED_PARTNERSHIP, WHEN_ISSUED, UNKNOWN ]

 */

public enum SapiTransactionEquityType: String, Codable, CaseIterable
{
    case COMMON_STOCK = "COMMON_STOCK"
    case PREFERRED_STOCK = "PREFERRED_STOCK"
    case DEPOSITORY_RECEIPT = "DEPOSITORY_RECEIPT"
    case RESTRICTED_STOCK = "RESTRICTED_STOCK"
    case COMPONENT_UNIT = "COMPONENT_UNIT"
    case RIGHT = "RIGHT"
    case WARRANT = "WARRANT"
    case CONVERTIBLE_PREFERRED_STOCK = "CONVERTIBLE_PREFERRED_STOCK"
    case CONVERTIBLE_STOCK = "CONVERTIBLE_STOCK"
    case LIMITED_PARTNERSHIP = "LIMITED_PARTNERSHIP"
    case WHEN_ISSUED = "WHEN_ISSUED"
    case UNKNOWN = "UNKNOWN"
}
