//
//  SapiFeeType.swift
//  ccSchwabManager
//
//  Created by Harold Tomlinson on 2025-04-27.
//

/*
 
 feeType    string
 Enum:
 [ COMMISSION, SEC_FEE, STR_FEE, R_FEE, CDSC_FEE, OPT_REG_FEE, ADDITIONAL_FEE, MISCELLANEOUS_FEE, FUTURES_EXCHANGE_FEE, LOW_PROCEEDS_COMMISSION, BASE_CHARGE, GENERAL_CHARGE, GST_FEE, TAF_FEE, INDEX_OPTION_FEE, UNKNOWN ]

 
 
 */
